### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by cambo32** [Giteob/Cheat-Loverz-Leak-Fortnite-External-Cheat#1]
![VS3](https://user-images.githubusercontent.com/102672909/160845233-cdf8ed1c-aae7-4eac-bd64-7eb6c106ac5e.png)
![VS4](https://user-images.githubusercontent.com/102672909/160845242-4e28d404-80eb-4d09-acf3-e8ffd4176c5a.png)
how to fix ?

**Comment by Giteob** [comment]
maybe project settings try MBCS instead Unicode
